#+TITLE: ox-org-hugo-sidenotes.el
#+AUTHOR: Robin Schroer

* Introduction

This package is scratching a very particular itch of mine, so YMMV.

It provides org-mode->org-mode export with slight modifications to
allow for using a theme with [[https://edwardtufte.github.io/tufte-css/][Tufte]]-style sidenotes.

The intended workflow is to maintain a directory of "clean" org files
outside Hugo's ~content~ directory, and export a "dirty" version from
there to Hugo's ~content~ directory. The dirty version will have
Hugo-specific markup, while the source will be regular org-mode.

The advantage gained from this is not having to litter non-org syntax
in your org-mode source files.

* Features

** Sidenotes

Footnotes are inlined to their location of reference and wrapped in
~{{< sidenote >}}~ shortcodes.

** Automatic publishing dates

The ~#+DATE~ is set automatically to the date of exporting.

** Relative links

File links are wrapped in ~{{< ref "other-page.org" >}}~, so that Hugo
inserts the correct link automatically when linking to another page.

* Installation

Just fetch it from MELPA.

#+begin_src emacs-lisp
;; package.el
(package-install 'ox-org-hugo-sidenotes)

;; use-package
(use-package ox-org-hugo-sidenotes
  :ensure t)

;; straight
(straight-use-package 'ox-org-hugo-sidenotes)
#+end_src

* Configuration

Here is the set of settings with their default values:

#+begin_src emacs-lisp
(setq
 ;; Add the date header automatically
 ox-org-hugo-sidenotes-add-date t
 ;; File export path
 ox-org-hugo-sidenotes-export-path "")
#+end_src

There is also a customisation group called ~org-hugo-sidenotes-export~.

* Usage

Simply call ~org-export-dispatch~ and select the options relevant to
you.

* Alternatives

[[https://github.com/kaushalmodi/ox-hugo][ox-hugo]] fills a similar niche, and is much more fully featured, but
exports to Markdown instead of org-mode. Hugo is actually pretty good
when it comes to handling org-mode, so I chose the path of least
change.
