version: 2.1

jobs:
  tests:
    docker:
      - image: silex/emacs:26-alpine
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            emacs --version
            emacs -q \
              --batch \
              -l ox-org-sidenotes.el \
              -l test/ox-org-sidenotes-test.el \
              -f ert-run-tests-batch-and-exit

workflows:
  tests:
    jobs:
      - tests
